import { z } from "zod"
import { AssetCreateInput } from "../src/server/schemas/asset"
import { EmployeeCreateInput } from "../src/server/schemas/employee"
import { RegisterUserInput } from "../src/server/schemas/user"

export const userSeed: z.infer<typeof RegisterUserInput>[] = [
  {
    name: "John Allen Delos Reyes",
    email: "jdelosreyes@fas.com",
    password: "##EHQ5cjR26=+B1PjjhV",
    user_type: "admin",
    profile: {
      first_name: "John Allen",
      last_name: "Delos Reyes",
      middle_name: "Redobla",
      date_of_birth: new Date(2000, 4, 20),
      gender: "Male",
      phone_no: "09954135867",
    },
    address: {
      street: "Blk 21 Lot 13",
      state: "Pulanglupa Uno",
      city: "Las Piñas City",
      country: "Philippines",
      zip: "1742",
    },
  },
  {
    name: "Clea Bernadette Payra",
    email: "cpayra@fas.com",
    password: "47MaD0A1QG9zY82YvtCw",
    user_type: "admin",
    profile: {
      first_name: "Clea Bernadette",
      last_name: "Payra",
      middle_name: "Domingo",
      date_of_birth: new Date(2000, 3, 19),
      gender: "Female",
      phone_no: "09457905387",
    },
    address: {
      street: "2206 Alacalde St.",
      state: "Brgy. 148",
      city: "City of Manila",
      country: "Philippines",
      zip: "1013",
    },
  },
  {
    name: "Franz Arvae Ignacio",
    email: "fignacio@fas.com",
    password: "8SapBWn3JCOTpET2ktfv",
    user_type: "admin",
    profile: {
      first_name: "Franz Arvae",
      last_name: "Ignacio",
      middle_name: "Montemayor",
      date_of_birth: new Date(2000, 4, 6),
      gender: "Male",
      phone_no: "09292045190",
    },
    address: {
      street: "Kapitan Tiago St.",
      state: "Acacia",
      city: "Malabon City",
      country: "Philippines",
      zip: "1474",
    },
  },
  {
    name: "Kevin Ralph Lauren Paular",
    email: "kpaular@fas.com",
    password: "$qZWvsyC@jaNvcA42=g9",
    user_type: "admin",
    profile: {
      first_name: "Kevin Ralph Lauren",
      last_name: "Paular",
      middle_name: "Butal",
      date_of_birth: new Date(1999, 8, 5),
      gender: "Male",
      phone_no: "09480494983",
    },
    address: {
      street: "Pelaez",
      state: "San Dionisio",
      city: "Parañaque City",
      country: "Philippines",
      zip: "1700",
    },
  },
  {
    name: "Klark Jasper Sisperez",
    email: "ksisperez@fas.com",
    password: "HCuzynjOeJKNNjpHq!=W",
    user_type: "admin",
    profile: {
      first_name: "Klark Jasper",
      last_name: "Sisperez",
      middle_name: "Peña",
      date_of_birth: new Date(1999, 8, 20),
      gender: "Male",
      phone_no: "09274974004",
    },
    address: {
      street: "Pilapil",
      state: "Brgy. 75",
      city: "City of Manila",
      country: "Philippines",
      zip: "1012",
    },
  },
]

export const employeeSeed: z.infer<typeof EmployeeCreateInput>[] = [
  {
    name: "John Allen Delos Reyes",
    email: "jdelosreyes@fas.com",
    employee_id: "EMP-01",
    department: "IT",
    position: "IT Manager",
    hired_date: new Date(2022, 7, 13),
    subsidiary: "eBizolution",
    profile: {
      first_name: "John Allen",
      last_name: "Delos Reyes",
      middle_name: "Redobla",
      date_of_birth: new Date(2000, 4, 20),
      gender: "Male",
      phone_no: "09954135867",
    },
    address: {
      street: "Blk 21 Lot 13",
      state: "Pulanglupa Uno",
      city: "Las Piñas City",
      country: "Philippines",
      zip: "1742",
    },
  },
  {
    name: "Clea Bernadette Payra",
    email: "cpayra@fas.com",
    employee_id: "EMP-02",
    department: "IT",
    position: "Principal UI/UX Designer",
    hired_date: new Date(2022, 7, 13),
    subsidiary: "eBizolution",
    profile: {
      first_name: "Clea Bernadette",
      last_name: "Payra",
      middle_name: "Domingo",
      date_of_birth: new Date(2000, 3, 19),
      gender: "Female",
      phone_no: "09457905387",
    },
    address: {
      street: "2206 Alacalde St.",
      state: "Brgy. 148",
      city: "City of Manila",
      country: "Philippines",
      zip: "1013",
    },
  },
  {
    name: "Franz Arvae Ignacio",
    email: "fignacio@fas.com",
    employee_id: "EMP-03",
    department: "IT",
    position: "Senior Web Developer",
    hired_date: new Date(2022, 7, 13),
    subsidiary: "eBizolution",
    profile: {
      first_name: "Franz Arvae",
      last_name: "Ignacio",
      middle_name: "Montemayor",
      date_of_birth: new Date(2000, 4, 6),
      gender: "Male",
      phone_no: "09292045190",
    },
    address: {
      street: "Kapitan Tiago St.",
      state: "Acacia",
      city: "Malabon City",
      country: "Philippines",
      zip: "1474",
    },
  },
  {
    name: "Kevin Ralph Lauren Paular",
    email: "kpaular@fas.com",
    employee_id: "EMP-04",
    department: "IT",
    position: "Senior Mobile Developer",
    hired_date: new Date(2022, 7, 13),
    subsidiary: "eBizolution",
    profile: {
      first_name: "Kevin Ralph Lauren",
      last_name: "Paular",
      middle_name: "Butal",
      date_of_birth: new Date(1999, 8, 5),
      gender: "Male",
      phone_no: "09480494983",
    },
    address: {
      street: "Pelaez",
      state: "San Dionisio",
      city: "Parañaque City",
      country: "Philippines",
      zip: "1700",
    },
  },
  {
    name: "Klark Jasper Sisperez",
    email: "ksisperez@fas.com",
    employee_id: "EMP-05",
    department: "IT",
    position: "Senior Software Engineer",
    hired_date: new Date(2022, 7, 13),
    subsidiary: "eBizolution",
    profile: {
      first_name: "Klark Jasper",
      last_name: "Sisperez",
      middle_name: "Peña",
      date_of_birth: new Date(1999, 8, 20),
      gender: "Male",
      phone_no: "09274974004",
    },
    address: {
      street: "Pilapil",
      state: "Brgy. 75",
      city: "City of Manila",
      country: "Philippines",
      zip: "1012",
    },
  },
]

export const classSeed: { name: string }[] = [
  { name: "Techonology" },
  { name: "Utitility" },
]

export const categorySeed: { name: string }[] = [
  { name: "Hardware" },
  { name: "Software" },
  { name: "Emergency" },
  { name: "Essentials" },
]

export const typeSeed: { name: string }[] = [
  { name: "Laptop" },
  { name: "Computer" },
  { name: "Application" },
  { name: "Fire Extinguisher" },
  { name: "Camera" },
]

export const assetSeed: z.infer<typeof AssetCreateInput>[] = [
  {
    name: "Macbook Pro 2022",
    serial_number: "123123233",
    description: "Laptop for work",
    number: "ASSET-01",
    current_cost: 50000,
    current_netbook_value: 40000,
    original_cost: 50000,
    categoryId: 1,
    typeId: 1,
    model: {
      name: "Macbook Pro",
      brand: "Apple",
      number: "2022",
    },
  },
  {
    name: "Fire Extinguisher Pro Max",
    serial_number: "123123233",
    description: "Fire Extinguisher for emergencies",
    number: "ASSET-02",
    current_cost: 50000,
    current_netbook_value: 40000,
    original_cost: 50000,
    categoryId: 3,
    typeId: 4,
    model: {
      name: "Pro Max",
      brand: "Katol",
      number: "2022",
    },
  },
]
